name: coin_wise
description: A new Flutter project.


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  date_range_form_field: ^1.0.2
  date_time_picker: ^2.1.0
  fl_chart: ^0.50.0
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.3.0
  flutter_datetime_picker: ^1.5.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  pandabar: ^0.1.2
  syncfusion_flutter_datepicker: ^20.1.48
  image_picker: ^0.8.2
  month_picker_dialog: ^0.4.0
  pie_chart: ^5.3.0
  awesome_notifications: ^0.0.6+7
  double_back_to_close_app: ^2.1.0
  url_launcher: ^6.0.3
dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  flutter_slidable: ^1.2.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./assets/images/log.jpg
  #  - ./assets/images/splashpic.jpg
    - ./assets/images/onboard1.jpg
    - ./assets/images/onboard2.png
    - ./assets/images/onboardlast.png

  fonts:
    - family: Antic
      fonts:
        - asset: ./assets/fonts/Antic-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Sans
      fonts:
        - asset: ./assets/fonts/EncodeSansExpanded-Light.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

